
SELECT * FROM customer LIMIT 10;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount)
FROM customer
GROUP BY gender
ORDER BY gender DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, AVG(purchase_amount)
FROM customer
WHERE discount_applie ('YES')

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


--Q10. Write a SQL query to find duplicate purchase records where same customer_id, Item_purchased, purchased_amount
SELECT customer_id, item_purchased, purchase_amount, COUNT(*)
FROM customer
GROUP BY customer_id, item_purchased, purchase_amount
HAVING COUNT(*) >1;


--Q11. Find total number of orders per customer.
SELECT customer_id, COUNT(item_purchased) AS No_OF_Orders
FROM customer
GROUP BY customer_id;

--Q12. Find customers who placed more than 5 orders.
SELECT customer_id, COUNT(*) AS No_OF_Orders
FROM customer
GROUP BY customer_id
HAVING COUNT(*) > 5;

--Q13. Find the most purchased item (by count)
SELECT item_purchased, COUNT(item_purchased) AS No_Of_Purchase
FROM customer
GROUP BY item_purchased
ORDER BY No_Of_Purchase DESC
LIMIT 1;

--Q14. Find total revenue generated per item.
SELECT item_purchased,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY item_purchased;


--Q15. 